### ISSUE TITLE
Cannot load http://localhost:9002/wp/site.js & http://localhost:9002/wp/site.css

### ISSUE THREAD

**Issue by zenflow** [apostrophecms/a3-boilerplate#26]
## To Reproduce

1. Start development server
2. Open a browser tab
3. Open Chrome devtools for that tab
4. Browse to http://localhost:3000/ in that tab
5. Observe console errors:
```
GET http://localhost:9002/wp/site.css net::ERR_CONNECTION_REFUSED
GET http://localhost:9002/wp/site.js net::ERR_CONNECTION_REFUSED
```

## Expected behavior

I expected not to find any errors in the devtools console.
I expected all page resources to load successfully.

## Describe the bug

The `views/layout.html` template references these two files when in dev mode (`data.isDev`), apparently "For live reload".
But the development server doesn't bind to port 9002 and doesn't serve these URLs.
Should these references be changed (to get some kind of live reload functionality)? 
Or should they be removed? (Perhaps it's some kind of cruft?)

**EDIT:** To be honest, I'm pretty OK with not having live reload on the front-end. Refreshing manually takes a single combination keystroke and lets me first decide if I'm done with that page load.
My main problem here is that each page load is delayed by a few seconds due to trying to connect to a port that's not listening for connections. So I think that should either be fixed, or we should just remove it like I've done (at least temporarily) in my project https://github.com/zenflow/apos-my-site/commit/2ba0352d93aecfbd7bd8d23c668d9565b0196bb3

## Details

**Version of Node.js:**
v14.18.0

From issue template:

> *PLEASE NOTE: Only stable LTS versions (10.x and 12.x) are fully supported but we will do our best with newer versions.*

Note that 10.x is past end-of-life and 14.x is officially moved from Active LTS to Maintenance LTS today actually

**Server Operating System:**
Windows 10

**Comment by boutell** [comment]
Thanks for pointing this out, it is indeed leftover cruft from before A3 had its own restart capability, you may remove it from your project.
